import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";
import ApolloClientProvider from "./components/ApolloProvider";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const firebaseConfig = {
  apiKey: "AIzaSyA1_xqN6NCEdFmvghxuci-nubcO36YJKQs",
  authDomain: "dice5000.firebaseapp.com",
  projectId: "dice5000",
  storageBucket: "dice5000.firebasestorage.app",
  messagingSenderId: "712696843903",
  appId: "1:712696843903:web:8a1d74a26c3406431ff94a",
  measurementId: "G-4DS9NF3N6S"
};
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen overflow-hidden`}
      >
        <ApolloClientProvider>
          <Nav></Nav>
          <main className="flex-1 overflow-hidden">
            {children}
          </main>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
